FROM indigodatacloud/ci-images:python3.6
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends  gdal-bin python3-gdal && \
    rm -rf /var/lib/apt/lists/*