# Docker image for CI testing of the DEEPaaS API
# Note there is probably no GPU in the CI server
ARG tag=1.14.0-py3
FROM tensorflow/tensorflow:${tag}
ENV FORCE_REBUILD=1

# Install GDAL and required tools
RUN apt-get update && \
    apt-get install -y \
        gdal-bin \
        python3-gdal && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN pip3 install --no-cache-dir --upgrade pip "setuptools<42" wheel "gdal>=2.2,<3"


RUN pip3 install --no-cache-dir tox

CMD ["sleep", "infinity"]
