# Docker image for CI testing of the DEEPaaS API
# Note there is probably no gpu in the CI server
ARG tag=1.14.0-py3
FROM tensorflow/tensorflow:${tag}
# Add PPA to get a newer version of GDAL
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt-get install -y \
        gdal-bin \
        python3-gdal \
        python3-pip && \
    pip3 install --upgrade pip "setuptools<58" wheel
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir --upgrade pip "setuptools<58"   wheel
RUN pip3 install --no-cache-dir tox
CMD ["sleep", "infinity"]
